sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  matrix:
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0

install:
  - pip install tox coveralls

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//./}-dj${DJANGO_VERSION//./},coverage

# report coverage to coveralls.io
after_success: coveralls

notifications:
  slack: tobalabs:XPt5OlsKuFGgIQZp0DpNXBUl

deploy:
  provider: pypi
  user: mwarkentin
  password:
    secure: "cQtAP8fMu+KzfBKG3ibTTXmDGZuz/FBp8RrLI8ddMGV4Jj5ElZLsvbqU43fiHbtVPV/uALDPF76WNGlpRH1P4w9m4XrFNCvkrnjtwIk7NZWi7uubWZcqQk9VE7MTP+i2IYrtNlGmlq1dbdJZcwS0mdzJcAAhAaP830Ekmqws9xE="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
