sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=1.7

install:
  - pip install tox coveralls

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//./}-dj${DJANGO_VERSION//./},coverage

# report coverage to coveralls.io
after_success: coveralls

notifications:
  slack: tobalabs:XPt5OlsKuFGgIQZp0DpNXBUl
